blue-geicos/Grace-Shopper

README.md, package-lock.json, script/seed.js, server/api/users.js, server/db/db.js, server/db/models/index.js, server/db/models/items.js, server/db/models/orders.js, server/db/models/user.js, server/index.js
---
closes #3, closes #4,  closes #5
=> Feat 3 4 5

server/api/index.js, server/api/items.js
=> added get route for all items, feat 6

server/api/items.spec.js
=> unit test for feat 6

script/seed.js, server/db/models/user.spec.js
=> completed tests for features 3, 4 ,5

client/store/items.js, client/store/items.spec.js, server/api/items.js
=> feature 21 complete

client/components/all-items.js, client/components/index.js, client/routes.js, client/store/index.js, client/store/items.js, script/seed.js, server/api/items.js, server/api/users.js, server/index.js
=> completed feat 7 all items

server/api/items.js
=> Completed route for single item

client/components/index.js, client/components/single-item.js, client/routes.js, client/store/items.js, server/api/items.js
=> feature 9- single item component

client/components/all-items.js, client/routes.js
=> completed feature 29

client/components/single-item.js, client/store/cart.js, server/api/index.js
=> completed feature #17

client/components/navbar.js, client/components/user-home.js, public/index.html, public/style.css
=> completed feat-33

client/components/single-item.js
=> completed deployment and refactored

client/components/all-items.js, client/components/auth-form.js, client/components/cart.js, client/components/single-item.js, client/store/cart.js, client/store/user.js, package-lock.json, script/seed.js, server/auth/index.js, server/db/models/index.js, server/db/models/items.js, server/db/models/order-items.js, server/db/models/user.js
=> Completed feat-38

client/components/navbar.js, client/store/cart.js, client/store/index.js, client/store/user.js
=> feat-46 user logout and clear localStorage

client/app.js, client/components/auth-form.js, client/components/cart-item.js, client/components/cart-summary.js, client/components/navbar.js, client/components/user-home.js, public/index.html, public/style.css
=> minor changes to font and home page

client/components/cart-summary.js, client/components/cart.js, client/store/cart.js, package-lock.json, package.json, server/api/orders.js, server/api/users.js
=> added stripe charge creation to orders api

client/components/cart-item.js, client/components/cart.js, client/components/checkout/checkout-container.js, client/components/userNavBar.js, server/db/models/index.js
=> changed styling for logout button

client/components/error-page.js, client/components/index.js, client/components/navbar.js, client/components/user-home.js, client/routes.js, public/style.css, server/api/index.js
=> feat-83 error handling page plus minor CSS and image changes

client/components/all-items.js, client/components/auth-form.js, client/components/cart.js, client/components/index.js, client/components/user-home.js, client/index.js, client/routes.js, client/store/cart.js, client/store/checkout.js, client/store/items.js, client/store/user.js, public/style.css, script/seed.js, server/api/users.js
=> AK Cleanup for feat-89

client/components/all-items.js, client/components/checkout/payment.js, client/components/checkout/shipping.js
---
closes #93, closes #55, closes #55, closes #82
=> Further cleanup in cart components

client/store/cart.js
=> fixed quantity badge
